/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pruebajsp.proyectoroman.vista;

import com.pruebajsp.proyectoroman.logica.Controladora;
import com.pruebajsp.proyectoroman.logica.Odontologo;
import com.pruebajsp.proyectoroman.logica.Paciente;
import com.pruebajsp.proyectoroman.persistencia.exceptions.NonexistentEntityException;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 * Clase que representa la interfaz gráfica para gestionar odontólogos y sus
 * pacientes. Permite crear, eliminar y visualizar odontólogos, así como acceder
 * a otras funcionalidades como la facturación total y la gestión de gastos.
 *
 * @author Lopez Martin
 */
public class VerPacienteVista extends javax.swing.JFrame {

    /**
     * Controladora que gestiona la lógica de negocio relacionada con
     * odontólogos y pacientes.
     */
    Controladora control = new Controladora();

    public VerPacienteVista() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.cargarTablaOdontologo();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/META-INF/medical-59_icon-icons.com_73933.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCrearPaciente1 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaOdontologos = new javax.swing.JTable();
        btnCrearOdontologo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnEliminarOdontologo = new javax.swing.JButton();
        btnFacturacionTotal = new javax.swing.JButton();
        btnCrearPaciente = new javax.swing.JButton();
        btnGastos = new javax.swing.JButton();
        txtNombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnCrearPaciente1.setBackground(new java.awt.Color(153, 153, 153));
        btnCrearPaciente1.setText("crear paciente");
        btnCrearPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPaciente1ActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(183, 63, 65));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/volver.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "ODONTÓLOGOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel5.setText("NOMBRE:");

        tablaOdontologos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaOdontologos);

        btnCrearOdontologo.setBackground(new java.awt.Color(33, 150, 243));
        btnCrearOdontologo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCrearOdontologo.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearOdontologo.setText("crear");
        btnCrearOdontologo.setBorder(BorderFactory.createLineBorder(new Color(33, 150, 243), 2, true));
        btnCrearOdontologo.setFocusPainted(false);
        btnCrearOdontologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearOdontologoActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "OPCIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnEliminarOdontologo.setBackground(new java.awt.Color(33, 150, 243));
        btnEliminarOdontologo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEliminarOdontologo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarOdontologo.setText("ELIMINAR");
        btnEliminarOdontologo.setBorder(BorderFactory.createLineBorder(new Color(33, 150, 243), 2, true));
        btnEliminarOdontologo.setFocusPainted(false);
        btnEliminarOdontologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarOdontologoActionPerformed(evt);
            }
        });

        btnFacturacionTotal.setBackground(new java.awt.Color(33, 150, 243));
        btnFacturacionTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFacturacionTotal.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturacionTotal.setText("FACTURACIÓN TOTAL");
        btnFacturacionTotal.setBorder(BorderFactory.createLineBorder(new Color(33, 150, 243), 2, true));
        btnFacturacionTotal.setFocusPainted(false);
        btnFacturacionTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionTotalActionPerformed(evt);
            }
        });

        btnCrearPaciente.setBackground(new java.awt.Color(33, 150, 243));
        btnCrearPaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCrearPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPaciente.setText("VER PACIENTES");
        btnCrearPaciente.setBorder(BorderFactory.createLineBorder(new Color(33, 150, 243), 2, true));
        btnCrearPaciente.setFocusPainted(false);
        btnCrearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPacienteActionPerformed(evt);
            }
        });

        btnGastos.setBackground(new java.awt.Color(33, 150, 243));
        btnGastos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGastos.setForeground(new java.awt.Color(255, 255, 255));
        btnGastos.setText("GASTOS");
        btnGastos.setBorder(BorderFactory.createLineBorder(new Color(33, 150, 243), 2, true));
        btnGastos.setFocusPainted(false);
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarOdontologo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFacturacionTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnGastos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnCrearPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarOdontologo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFacturacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtNombre1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        jLabel6.setText("DIRECCIÓN:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnCrearOdontologo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearOdontologo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        btnVolver1.setBackground(new java.awt.Color(183, 63, 65));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/volver.png"))); // NOI18N
        btnVolver1.setBorder(null);
        btnVolver1.setBorderPainted(false);
        btnVolver1.setFocusPainted(false);
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPaciente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPaciente1ActionPerformed

    /**
     * Método que se ejecuta cuando se hace clic en el botón "Crear Paciente".
     * Abre la vista para crear un nuevo paciente asociado al odontólogo
     * seleccionado.
     *
     * @param evt Evento de acción generado por el clic en el botón.
     */
    private void btnCrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPacienteActionPerformed
        if (tablaOdontologos.getRowCount() > 0) {
            if (tablaOdontologos.getSelectedRow() != -1) {
                long id_odontologo = Integer.parseInt(String.valueOf(tablaOdontologos.getValueAt(tablaOdontologos.getSelectedRow(), 0)));
                Odontologo odontologo = control.traerOdontologo(id_odontologo);
                CrearPacienteVista crearPacienteVista = new CrearPacienteVista(odontologo);
                this.dispose();

            } else {
                VistaUtils.mostrarMensaje("No se selecciono ningún odontologo", "error", "Error al seleccionar");

            }
        } else {
            VistaUtils.mostrarMensaje("No hay nada para seleccionar en la tabla", "error", "Error al seleccionar");

        }
    }//GEN-LAST:event_btnCrearPacienteActionPerformed

    /**
     * Método que se ejecuta cuando se hace clic en el botón "Crear Odontólogo".
     * Valida los campos de entrada y crea un nuevo odontólogo en la base de
     * datos.
     *
     * @param evt Evento de acción generado por el clic en el botón.
     */
    private void btnCrearOdontologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearOdontologoActionPerformed
        String nombre = txtNombre.getText();
        String direccion = txtNombre1.getText();
        if (nombre == null || nombre.isEmpty() || direccion == null || direccion.isEmpty()) {
            VistaUtils.mostrarMensaje("Hay campos sin completar", "error", "Error al guardar");
            return;
        } else {
            control.crearOdontologo(nombre, direccion);
            VistaUtils.mostrarMensaje("Odontólogo creado correctamente", "info", "guardado exitosamente");
            this.cargarTablaOdontologo();
            txtNombre.setText("");
            txtNombre1.setText("");
        }

    }//GEN-LAST:event_btnCrearOdontologoActionPerformed

    /**
     * Método que se ejecuta cuando se hace clic en el botón "Eliminar
     * Odontólogo". Elimina el odontólogo seleccionado en la tabla después de
     * confirmar la acción.
     *
     * @param evt Evento de acción generado por el clic en el botón.
     */
    private void btnEliminarOdontologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarOdontologoActionPerformed
        Odontologo odontologo = null;

        if (tablaOdontologos.getRowCount() > 0) {
            if (tablaOdontologos.getSelectedRow() != -1) {
                long id_odontologo = Integer.parseInt(String.valueOf(tablaOdontologos.getValueAt(tablaOdontologos.getSelectedRow(), 0)));
                odontologo = control.traerOdontologo(id_odontologo);

                boolean confirmacion = VistaUtils.mostrarConfirmacion(this,
                        "Estas seguro que deseas eliminar al odontologo con el nombre " + odontologo.getNombre() + " se borraran todos sus pacientes",
                        "Confirmacion de eliminacion"
                );

                if (confirmacion) {
                    try {
                        control.eliminarOdontologo(id_odontologo);

                    } catch (NonexistentEntityException ex) {
                        Logger.getLogger(CrearPacienteVista.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    VistaUtils.mostrarMensaje("Odontologo eliminado correctamente", "info", "Eliminacion correcta");
                    this.cargarTablaOdontologo();
                } else {
                    VistaUtils.mostrarMensaje("Operacion de eliminacion cancelada", "info", "Operacion cancelada");
                }

            } else {
                VistaUtils.mostrarMensaje("No se selecciono ningún odontologo", "error", "Error al editar");

            }
        } else {
            VistaUtils.mostrarMensaje("No hay nada para eliminar en la tabla", "error", "Error al editar");

        }
    }//GEN-LAST:event_btnEliminarOdontologoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * Método que se ejecuta cuando se hace clic en el botón "Volver". Cierra la
     * ventana actual y abre la ventana principal.
     *
     * @param evt Evento de acción generado por el clic en el botón.
     */
    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        this.dispose();
        Principal principal = new Principal();

    }//GEN-LAST:event_btnVolver1ActionPerformed

    /**
     * Método que se ejecuta cuando se hace clic en el botón "Facturación
     * Total". Abre la vista de facturación total.
     *
     * @param evt Evento de acción generado por el clic en el botón.
     */
    private void btnFacturacionTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionTotalActionPerformed
        FacturacionTotalVista facturacionVista = new FacturacionTotalVista();
    }//GEN-LAST:event_btnFacturacionTotalActionPerformed

    /**
     * Método que se ejecuta cuando se hace clic en el botón "Gastos". Abre la
     * vista de gestión de gastos y cierra la ventana actual.
     *
     * @param evt Evento de acción generado por el clic en el botón.
     */
    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
        GastosVista gastosVista = new GastosVista();
        this.dispose();
    }//GEN-LAST:event_btnGastosActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal principal = new Principal();
    }//GEN-LAST:event_formWindowClosing

    /**
     * Método que carga los datos de los odontólogos en la tabla. Obtiene los
     * datos de la controladora y los muestra en la tabla.
     */
    public void cargarTablaOdontologo() {
        tablaOdontologos.setRowHeight(30);
        DefaultTableModel modelotabla = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        List<Odontologo> odontologos = control.traerListaOdontologos();
        System.out.println("Pacientes encontrados: " + odontologos.size());

        String titulo[] = {"id", "Nombre", "Dirección"};
        modelotabla.setColumnIdentifiers(titulo);

        for (Odontologo odontologo : odontologos) {
            Object objeto[] = {odontologo.getIdOdontologo(), odontologo.getNombre(), odontologo.getDireccion()};
            modelotabla.addRow(objeto);
        }

        tablaOdontologos.setModel(modelotabla);
        // Suponiendo que "tablaPacientes" es tu JTable
        TableColumnModel columnModel = tablaOdontologos.getColumnModel();

        // Ajustamos el ancho de cada columna
        /*tablaOdontologos.getColumnModel().getColumn(0).setMinWidth(0);
        tablaOdontologos.getColumnModel().getColumn(0).setMaxWidth(0);*/
        tablaOdontologos.getColumnModel().getColumn(0).setWidth(5);   // ID (más pequeño)
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(250);
        tablaOdontologos.setBackground(new java.awt.Color(255, 255, 255));
        tablaOdontologos.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        tablaOdontologos.setFont(new java.awt.Font("Arial", 0, 12));// Nombre (más grande)

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearOdontologo;
    private javax.swing.JButton btnCrearPaciente;
    private javax.swing.JButton btnCrearPaciente1;
    private javax.swing.JButton btnEliminarOdontologo;
    private javax.swing.JButton btnFacturacionTotal;
    private javax.swing.JButton btnGastos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaOdontologos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
